Repository prototypal/web3torrent-pse, pull requests merged in 2019-09, with the labels that each got.

#3 fix Interval clearing on Download complete
  src/index.js
Labels: bug

#4 Leecher to seeder
  src/constants.js
  src/index.js
  src/styles.css
  src/webtorrent-custom.js
  src/wire-extension.js
Labels: bug, enhancement

#6 Add a mini docs
  README.md
Labels: documentation

#8 Implements Web3Torrent tests
  .gitignore
  jest.config.js
  package.json
  src/web3torrent-lib.js
  tests/basic-functionality.test.js
  tests/client-seeding.test.js
  tests/setup.js
  tests/teardown.js
  yarn.lock
Labels: testing

#13 Rewrites the codebase in TypeScript
  jest.config.js
  package.json
  src/constants.js
  src/index.tsx
  src/paid-streaming-extension.ts
  src/pse-middleware.ts
  src/react-app-env.d.ts
  src/types.ts
  src/web3torrent-lib.js
  src/web3torrent-lib.ts
  src/wire-extension.js
  tests/basic-functionality.test.ts
  tests/client-seeding-leeching.test.ts
  tests/client-seeding.test.ts
  tests/utils.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: enhancement

#14 add more time-testing and parallel tests
  package.json
  tests/client-seeding-leeching.test.ts
  tests/time-based-leeching/leeching-125000.test.ts
  tests/time-based-leeching/leeching-35000.test.ts
  tests/time-based-leeching/leeching-5000.test.ts
  tests/time-based-leeching/leeching-65000.test.ts
Labels: testing

#15 improve logs
  package.json
  src/index.tsx
  src/paid-streaming-extension.ts
  src/web3torrent-lib.ts
  yarn.lock
Labels: enhancement
